#include "arduino_secrets.h"
#include <DHTesp.h>
#include "thingProperties.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/84f9199b-9176-4935-943e-8f5de8535d0e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float sensor_DHT22_Humedad;
  float sensor_DHT22_Temperatura;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  Serial.begin(9600);
  delay(1500); 
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  dht.setup(4,DHTesp::DHT22);
}

void loop() {
  ArduinoCloud.update();
  sensor_DHT22_Temperatura = dht.getTemperature();
  sensor_DHT22_Humedad = dht.getHumidity();
  delay(5000);
  Serial.print("Humidity (%): ");
  Serial.println(sensor_DHT22_Humedad, 2);

  Serial.print("Temperature  (C): ");
  Serial.println(sensor_DHT22_Temperatura, 2);
}





