// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4bbe784e-9554-44ac-9340-713098b99acd";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFocoChange();
void onContadorChange();

float sensor_DHT22_Humedad;
float sensor_DHT22_Temperatura;
int contador;
bool foco;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sensor_DHT22_Humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sensor_DHT22_Temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contador, READWRITE, ON_CHANGE, onContadorChange);
  ArduinoCloud.addProperty(foco, READWRITE, ON_CHANGE, onFocoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
